### ISSUE TITLE
Link and handle similar notifications

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#35] opened 2020-06-03 20:55 UTC
- As a back office employee, I want to be able to link notifications so that a double notification only needs to be handled once.

- As a back office employee, I want all reporters of linked notifications to receive the same status updates so that multiple reporters are informed with one action.

**Comment by bartjkdp** [comment] 2020-07-22 18:43
Duplicate of Signalen/backend#56

**Closed by bartjkdp** 2020-07-22 18:43 UTC
Labels: phase 2
